# -*- coding: utf-8 -*-
"""Cognifyz1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4cQ6miK60UGeVYS3Ug_b17OUPErSRTu

#LEVEL 1

## TASK 1
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

#load the dataset
df=pd.read_csv(r"/content/drive/MyDrive/Dataset_01.csv")
df.head()

#Names of coloumns and rows
df.shape

"""#1.1 Determine the top three common used cuisines"""

cuisine_count=df['Cuisines'].str.split(',',).explode().value_counts()

top_three_cuisine=cuisine_count.head(3)
print(top_three_cuisine)

top_three_cuisine=top_three_cuisine.sort_values(ascending=False)

fig,Ax=plt.subplots(figsize=(10,6))
sns.barplot(x=top_three_cuisine.index,y=top_three_cuisine.values,ax=Ax)
plt.title("Top Three Most Common Cuisines")
plt.xlabel("Cuisine")
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""#1.2 Calculate the %of Restaurants that serve each of top cuisines"""

top_restaurants=len(df)
percentage_per_cuisine=(top_three_cuisine/top_restaurants)*100
print(percentage_per_cuisine)

print("Percentage of restaurants for top three cuisines")
percentage_per_cuisine

fig,ax=plt.subplots(figsize=(10,6))

ab=sns.barplot(x=percentage_per_cuisine.index,y=percentage_per_cuisine.values)
for bar in ab.containers[0]:
  height=bar.get_height()
  ab.annotate(f'{height:.2f}%',xy=(bar.get_x()+bar.get_width()/2,height),xytext=(0,3),textcoords='offset points',ha='center',va='bottom')
plt.title("Percentage of Restaurants serving top three cuisines")

"""##### Task 1 completed...

#TASK 2

###Task:City analysis
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv(r"/content/drive/MyDrive/Dataset_01.csv")
df.head()

df.shape
df.info()

"""####Identify the city with the highest number of restaurants"""

print(df["City"].value_counts()[[0]].index[0])

"""#Calculate the average for restaurants in a each day"""

average_restaurent_rating=df.groupby('City').agg(Average_rating=('Aggregate rating','mean')).sort_values(by='Average_rating',ascending=False)
print(average_restaurent_rating)

plt.subplots(figsize=(20,100))
average_restaurent_rating=df.groupby('City').agg(Average_rating=('Aggregate rating','mean')).sort_values(by='Average_rating',ascending=False)
sns.barplot(x='Average_rating',y=average_restaurent_rating.index,data=average_restaurent_rating)
bars=plt.bar(average_restaurent_rating.index,average_restaurent_rating['Average_rating'])
for bar in bars:
  plt.text(bar.get_width(),bar.get_x(),str(round(bar.get_width(),2)),ha='left',va='center')

plt.title("Average ratings of restaurents in each city")
plt.xlabel("Average Rating")
plt.ylabel("City")
plt.show()

"""####The city with the highest average"""

average_restaurent_rating=df.groupby('City').agg(average_rating=('Aggregate rating','mean')).sort_values(by='average_rating',ascending=False)
print("The city with the highest average rating is",average_restaurent_rating.index[0])

"""######Task 2 completed...

#TASK3

##Loading dataset
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv(r"/content/drive/MyDrive/Dataset_01.csv")
df.head()

df.shape

df.info()

plt.subplots(figsize=(10,6))
plt.hist(df['Price range'],bins=df['Price range'].nunique(),edgecolor='black')
plt.title('Price Range Distribution')
plt.xlabel('Price Range')
plt.ylabel('Frequency')
plt.show()

"""####Calculate the percentage of restraurents in each price range category"""

price_range_counts=df["Price range"].value_counts().reset_index()
price_range_counts

import pandas as pd

price_range_counts=df['Price range'].value_counts().reset_index()
total_restaurants=len(df)
percentage_per_price_range=df['Price range'].value_counts(normalize=True)*100

print("Percentage of restaurants in each price range category")
for price_range,percentage in percentage_per_price_range.items():
  print(f"Price Range {price_range}: {percentage:.2f}%")

fig,ax=plt.subplots(figsize=(10,6))
percentage_per_price_range.plot(kind='bar',ax=ax,color='green')
for bar in ax.containers[0]:
  height=bar.get_height()
  ax.annotate(f'{height:.2f}%',xy=(bar.get_x()+bar.get_width()/2,height),xytext=(0,3),textcoords='offset points',ha='center',va='bottom')
plt.title("Percentage of Restaurants in Each Price Range Category")
plt.xlabel("Price Range")
plt.ylabel("Frequency")
plt.show()

"""#TASK 4"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv(r"/content/drive/MyDrive/Dataset_01.csv")
df.head()

df.info()

total_online_delivery_restaurents=len(df[df['Has Online delivery']=='Yes'])
total_restaurents=len(df)
percentage_online_delivery=(total_online_delivery_restaurents/total_restaurents)*100
print("Percentage of online delivery restaurents:",percentage_online_delivery)

"""###The average rating of restaurents with or without online delivery"""

restaurents_with_online_delivery=df[df['Has Online delivery']=='Yes']
average_rating_with_online_delivery=restaurents_with_online_delivery['Aggregate rating'].mean()
print("Average rating of restaurents with online delivery:",average_rating_with_online_delivery)

restaurents_without_online_delivery=df[df['Has Online delivery']=='No']
average_rating_without_online_delivery=restaurents_without_online_delivery['Aggregate rating'].mean()
print("Average rating of restaurents without online delivery:",round(average_rating_without_online_delivery,2))

"""###TASK 4 completed..."""